name: hanzo
description: A library to easily use git hooks from Dart.
version: 1.0.3
homepage: https://github.com/andresaraujo/hanzo
author: Andres Araujo <a.araujo.azua@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  args: ^2.3.1
  io: ^1.0.3
  build_cli: ^2.2.0
  build_cli_annotations: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.0
  test: ^1.21.4
  grinder: ^0.9.2

executables:
  hanzo: hanzo
